const textDataDummy = [
  { label: 'H', active: 0 },
  { label: 'I', active: 0 },
  { label: ',&nbsp;', active: 0 },
  { label: 'I', active: 0 },
  { label: '’', active: 0 },
  { label: 'M', active: 0 },
  { label: '&nbsp;', active: 0 },
  { label: 'H', active: 1 },
  { label: 'O', active: 0 },
  { label: 'A', active: 0 },
  { label: 'N', active: 0 },
  { label: 'G', active: 0 },
  { label: '', active: 2 },
  { label: 'F', active: 1 },
  { label: 'R', active: 0 },
  { label: 'O', active: 0 },
  { label: 'N', active: 0 },
  { label: 'T', active: 0 },
  { label: '-', active: 1 },
  { label: 'E', active: 0 },
  { label: 'N', active: 0 },
  { label: 'D', active: 0 },
  { label: '&nbsp;', active: 0 },
  { label: 'D', active: 0 },
  { label: 'E', active: 0 },
  { label: 'V', active: 0 },
  { label: 'E', active: 0 },
  { label: 'L', active: 0 },
  { label: 'O', active: 0 },
  { label: 'P', active: 0 },
  { label: 'E', active: 0 },
  { label: 'R', active: 0 },
  { label: '&#9679;', active: 1 },
];

export default textDataDummy;
